### ISSUE TITLE
Wedge specific and non-specific code

### ISSUE THREAD

**Issue by mwilliams-ct** [facebook/openbmc#10]
Hi,

I've been working my way through the openBMC code, in particular the new software in userspace which I understand to be in meta-openbmc/meta-facebook/meta-wedge/recipes-wedge.

It seems to me that several of these apps shouldn't be in this layer as they don't appear to be Wedge specific. These are:

* fblibs/ipmi
* Some of ipmid (which also contains platform specific code)
* rackmon (though I should note that I am not certain on this as I am not fluent enough in C)
* usb-console

In addition, I would suggest the following software needs to be modified to decouple platform dependent code:

* oob_nic
* sms-kcs
* alert_control

It could be that I have misunderstood your intentions, and you would rather these did stay where they are and remain platform dependent. Either way, I'd be grateful if you could let me know your opinions.

Thanks in advance for your time!

**Comment by tfangit** [comment]
Yes. Some packages that are current in wedge board layer can be re-used by other boards. We are in the process to move such packages into common layer.
