### ISSUE TITLE
Removal of `yocto_repos.sh` breaks `sync_yocto.sh` script

### ISSUE THREAD

**Issue by lhl2617** [facebook/openbmc#121]
0941903 

There's a mentioned of "Moving the file to main" - but I was unable to find it elsewhere - this breaks `sync_yocto.sh`.

**Comment by amithash** [comment]
Thanks for reporting this issue! The fix should be coming asap.

**Comment by amithash** [comment]
Just landed: https://github.com/facebook/openbmc/commit/8063055bb2f48a865a86866c95d70735e013c1b9

This should be fixed now.

**Comment by lhl2617** [comment]
Thank you!
