### ISSUE TITLE
Fetcher failure

### ISSUE THREAD

**Issue by lisseni** [facebook/openbmc#123]
Hi, guys!
I try to build meta-fbtp at first time, but rsyslog is unreachable to download

ERROR: rsyslog-8.34.0-r0 do_fetch: Fetcher failure for URL: 'http://www.rsyslog.com/download/files/download/rsyslog/rsyslog-8.34.0.tar.gz'. Unable to fetch URL from any source.
ERROR: rsyslog-8.34.0-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /store/openbmc/meta-facebook/meta-fbtp/tmp/work/armv6-fb-linux-gnueabi/rsyslog/8.34.0-r0/temp/log.do_fetch.14117
ERROR: Task (/store/openbmc/yocto/rocko/poky/../../../common/recipes-extended/rsyslog/rsyslog_8.34.0.bb:do_fetch) failed with exit code '1'

What you would advice?

**Comment by williamspatrick** [comment]
Issue seems to have been with the rsyslog servers and is now resolved.
