### ISSUE TITLE
Docs  on ast2600 boot procedure

### ISSUE THREAD

**Issue by dineshkumarv86** [facebook/openbmc#128]
Hi all,
Is it any docs available which explaining the  boot procedure on ast2600 using openbmc images ?

**Comment by dagilson-ciena** [comment]
I am also interested in this.  We have an eval board coming in with an AST2600 on it.  

In the absence of being able to build a AST2600 image,  which build would be good to use that supports an AST2500?

**Comment by dagilson-ciena** [comment]
I am also interested in this.  We have an eval board coming in with an AST2600 on it.  

In the absence of being able to build a AST2600 image,  which build would be good to use that supports an AST2500?

**Comment by williamspatrick** [comment]
Can I get some more information on what you're looking for here?  The AST2600 isn't really any different from the AST2500 from our code's perspective.  u-boot is loaded out of SPI, loads the kernel, runs a rootfs.  I'm guessing you're looking for more details than that but I don't know what.
