### ISSUE TITLE
Redfish supportive

### ISSUE THREAD

**Issue by leilanon** [facebook/openbmc#141]
Hi, 
To support a few Redfish API, we had made a Redfish generator to create necessary api routes and responded handlers with simple platform configuration in JSON format. Currently we were using the tool at board layer, but is it better to use as in common layer, if we like to make it contribute to this repository?

**Comment by williamspatrick** [comment]
@leilanon - Yes, of course.  If you'd like to make a contribution we can take a look.  Go ahead and open a PR.  There has been some interest in supporting Redfish lately.
