### ISSUE TITLE
Clone meta-openbmc error: Permission Denied (publickey)

### ISSUE THREAD

**Issue by hoanganhbui** [facebook/openbmc#15]
I can't clone repository meta-openbmc with
git clone git@github.com:facebook/openbmc.git meta-openbmc

It say that:
anhbh@ubuntu:~/wedge/poky$ git clone git@github.com:facebook/openbmc.git meta-openbmc
Cloning into 'meta-openbmc'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Anyone has solution? Tks.

**Comment by shenki** [comment]
There are two solutions:

1. Add your ssh public key to your github account
2. Clone from https instead: ```git clone https://github.com/facebook/openbmc meta-openbmc```

**Comment by hoanganhbui** [comment]
Solved! thank you Shenki

**Comment by tfangit** [comment]
Thx, @shenki .
