### ISSUE TITLE
Build OpenBMC for VmWare x86

### ISSUE THREAD

**Issue by hoanganhbui** [facebook/openbmc#16]
Hi all, I've built an version of OpenBMC but for Wedge machine. 
Now I need to build another for virtual machine x86 to test it, I changed MACHINE = "qemux86" in file local.conf but it didn't work.
Did I do wrong? Or there are some other steps that I need to do?
Please help me!!!
Thank you

**Comment by theopolis** [comment]
Hi @hoanganhbui, you're not doing it "wrong" per say, OpenBMC just doesn't support the QUEMUX86 target machine right now. I don't think there are any near-term plans for support, but let us know if you'd be interested in working on this.
