### ISSUE TITLE
Fboss and compute platform

### ISSUE THREAD

**Issue by ChuTingI** [facebook/openbmc#193]
Hi all,

I am studying rest-api recently. When I was studying `redfish_chassis_helper.py` to figure out which fru tool the path `/redfish/v1/Chassis/1` use, I found the description about `fboss` and `compute` in the function `get_fru_info()`.
I want to know the difference between these two platforms and which is better for ast2600.
![image](https://user-images.githubusercontent.com/103412587/177094375-0c79060a-bb22-4986-969b-55658f720958.png)

Thank you

**Comment by williamspatrick** [comment]
"FBOSS" is for our switch platforms and "Compute" is for our more traditional compute / storage platforms.  Which one you pick is probably more dependent on what your server purpose is.

Are you building a system working with Meta or are you building your own system?  If you're building your own system then looking at https://github.com/openbmc/openbmc is probably more appropriate for your needs.
