### ISSUE TITLE
openbmc-init-build-env error

### ISSUE THREAD

**Issue by luoshuai777** [facebook/openbmc#198]
I want to generate a new machine, so I deleted the build/conf directory, and when I re-use source openbmc-init-build-env, an error occurs.

picky@ubuntu-local:~/Facebook/openbmc$ rm build/conf/ -rf
picky@ubuntu-local:~/Facebook/openbmc$ export TEMPLATECONF=/home/picky/Facebook/openbmc/meta-facebook/meta-fbep/conf
picky@ubuntu-local:~/Facebook/openbmc$ source openbmc-init-build-env emeraldpools
WARNING: Environment already set up for /home/picky/Facebook/openbmc/build
picky@ubuntu-local:~/Facebook/openbmc$ 

I need your help. Thank you！

**Comment by doranand** [comment]
Hi @luoshuai777.  Unfortunately, running openbmc-init-build-env more than once in a shell session is not currently supported.  To re-initialise the build environment, open a new shell / terminal and run the command there.  I hope this helps.
