### ISSUE TITLE
Setup Jenkins/Docker continuous build for Wedge/Wedge100/Yosemite images

### ISSUE THREAD

**Issue by theopolis** [facebook/openbmc#24]
Each PR (and commit to master) should trigger a Wedge/Wedge100/Yosemite incremental build. We can follow some of the recommended Docker/Yocto examples for building incremental layer configurations.

**Comment by linlynn** [comment]
Is that something I can help? @theopolis

**Comment by theopolis** [comment]
We should be good to go here! The README has the links to the Jenkins jobs. :)
