### ISSUE TITLE
Beside CentOS 6.X , any other oS supported, how about Fedora, Ubuntu ??

### ISSUE THREAD

**Issue by jwang3089** [facebook/openbmc#3]
Hi,

Any other OS is supported for this BMC, like Fedora or Ubuntu and the versions??

Regards

**Comment by linlynn** [comment]
if you are talking about build enviornment for openBMC , I think yes ,it support ubuntu/fedora,if you need more details ,here is link https://www.yoctoproject.org/documentation

**Comment by tfangit** [comment]
@jwang3089 Yes. Ubuntu/fedora are supported. There is an issue (#2) reported on using some version of make. @linlynn provided the patch for that.
