### ISSUE TITLE
Question about IPMI interface support: SOL, etc

### ISSUE THREAD

**Issue by yayake** [facebook/openbmc#30]
the openbmc seems only support IPMI's KCS messge interface, about other message interface(such as LAN, serial/modem) is not support. While openbmc may support SOL, without lan and serial interface, the SOL function seem useless.

**Comment by williamspatrick** [comment]
On Tue, Apr 12, 2016 at 01:00:53AM -0700, yayake wrote:
> the openbmc seems only support IPMI's KCS messge interface, about other message interface,such as LAN, serial/modem. While openbmc may support SOL, without lan and serial interface, the SOL function seem useless.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/facebook/openbmc/issues/30

We have implemented an application that can route the VUART of the host
to a number of different locations.  See
https://github.com/openbmc/obmc-console .

I believe we currently use this to route over an SSH connection, but
@jk-ozlabs could fill in more details on what we currently do and what
we are considering doing in the future.

-- 
Patrick Williams

**Comment by yayake** [comment]
e, over an ssh connection?
why not implements RMCP+ protocol, according to standard IPMI  v2.0.
recently, I'm little confuse about the function of openbmc's project, compared to bmc running in server.
Openbmc is only focused on little witch box?

**Comment by williamspatrick** [comment]
The current implementations did not have a need (or desire) for IPMI, due to the data centers they were being deployed into.  We recognize for a general-purpose / commercial server market IPMI is desirable but it has not been implemented yet.

**Comment by theopolis** [comment]
I'm closing this issue since the discussion has trailed off.
