### ISSUE TITLE
bitbake failure due to explicit protocol git in u-boot recipes not supported by firewall

### ISSUE THREAD

**Issue by an0maly** [facebook/openbmc#31]
Not all corporate firewalls support git protocol, nor do gitproxy configuration/scripts necessarily work.  However, http proxy usually is available.   

Modifying the meta-aspeed/recipes-bsp/u-boot/u-boot-fw-utils_2013.07.bb and meta-aspeed/recipes-bsp/u-boot/u-boot_2013.07.bb recipes with protocol=http resolved this issue.

**Comment by theopolis** [comment]
Thanks @an0maly, will fix!

**Comment by bcg62** [comment]
I'll open a separate issue but hit the same problem here

ERROR: Function failed: Fetcher failure for URL: 'git://github.com/theopolis/linux.git;branch=openbmc/fido/2.6.28;protocol=git'. Unable to fetch URL from any source.

**Comment by theopolis** [comment]
This should be fixed with 87e27c1aff7b266d7adc7370c069de274dee1e55, feel free to reopen or ping me if there are still issues. :)

**Comment by bcg62** [comment]
@theopolis got another one here.

WARNING: Failed to fetch URL git://sourceware.org/git/glibc.git;branch=release/2.21/master;name=glibc, attempting MIRRORS if available

**Comment by theopolis** [comment]
Ok, that's outside the scope of our `meta-` layer. Did `bitbake` succeed using the mirrors `glibc` defined?

**Comment by bcg62** [comment]
You're right it did, sorry spoke too soon.
