### ISSUE TITLE
Question about Redfish

### ISSUE THREAD

**Issue by curtbruns** [facebook/openbmc#35]
Hello,

Are there plans to support the Redfish/Swordfish APIs/schemas in the future?

Thanks,
Curt

**Comment by sdasari73** [comment]
We are evaluating Redfish API/schema against OpenBMC's existing REST API which are supported on various hardware platforms. At this time there is no time line to share. But if that feature is of interest on your hardware platform, we certainly are open to external contrbution/pull requests.

**Comment by vrpradeepkumar** [comment]
Hi,

Are there any design/plans to support Redfish in openbmc according to OCP?
Interested in contributing Redfish in openbmc.
Please share the details regarding it.

Thanks
Pradeep
