### ISSUE TITLE
README.md has incorrect build instructions

### ISSUE THREAD

**Issue by scott-emery** [facebook/openbmc#40]
The README.md has a "How to build" section which says to build using the fido branch. This is incorrect. It should list the krogoth branch instead.

**Comment by tfangit** [comment]
Ack.

**Comment by tfangit** [comment]
Before we push the latest README.md, here is the combination of Poky and OpenBMC branch for each board:

Poky (fido), openbmc (master): wedge, wedge100, galaxy100, yosemite
Poky (krogoth), openbmc (helium): cmm, fbtp, fbttn, lightning, fby2.

Wedge, wedge100, are galaxy100 are all moving to poky(krogoth)/openbmc(helium).

**Comment by scott-emery** [comment]
The documentation has been updated.
