### ISSUE TITLE
Update reference source for Intel IPMI specification document.

### ISSUE THREAD

**Issue by gbala88** [facebook/openbmc#42]
The reference hyperlink to IPMI specification:
 * http://www.intel.com/content/www/us/en/servers/ipmi/ipmi-specifications.html

is broken. Need to be changed to the working link.

Possible reference:
http://www.intel.com/content/www/us/en/servers/ipmi/ipmi-second-gen-interface-spec-v2-rev1-1.html

**Comment by jda** [comment]
Where do you see the link to the IPMI specifications?
