### ISSUE TITLE
certificate-store.dts  is mssing?

### ISSUE THREAD

**Issue by yongli3** [facebook/openbmc#45]
During the bitbake, I received the "certificate-store.dts is missing" error for u-boot_2016.07.bb.

I cannot find the certificate-store.dts in these meta folders, How to get this file?

**Comment by theopolis** [comment]
I'll take a look, we shouldn't require the certificate DTS anymore, but this was a recent change.

**Comment by theopolis** [comment]
This should have been resolved with: https://github.com/facebook/openbmc/commit/72752d723b392e6907bb827067281fa056bab60b let me know if you're still seeing U-Boot build issues and we can re-open. :)
