### ISSUE TITLE
OpenBMC and kernels

### ISSUE THREAD

**Issue by karthikbgt** [facebook/openbmc#46]
Hi,

I find the following versions of kernel recipes are present, however unable to find the the one that is based on version 4.7 kernel which is claimed to be stable for AST25XX series.... Can someone kindly confirm the availability of the kernel 4.7 ?

https://github.com/facebook/openbmc/blob/helium/meta-facebook/meta-cmm/recipes-kernel/linux/files/defconfig  -> linux kernel 4.1.15  (CMM OpenBMC)
https://github.com/facebook/openbmc/blob/helium/meta-facebook/meta-wedge100/recipes-kernel/linux/files/defconfig -> linux kernel 4.1.15 (wedge-100)
https://github.com/facebook/openbmc/blob/helium/meta-facebook/meta-wedge/recipes-kernel/linux/files/defconfig ->  linux kernel 4.1.15 (wedge)
https://github.com/facebook/openbmc/blob/helium/meta-facebook/meta-galaxy100/recipes-kernel/linux/files/defconfig   -> linux kernel 2.6.28.9 (OpenBMC for LC/FC )

Also, the code in below link (AST2520 header) states 2 versions as preferred. However i find that 4.7 is commented with '#'. Does it mean that the kernel version 4.7 is not supported ...
Reference : https://github.com/facebook/openbmc/blob/helium/meta-aspeed/conf/machine/include/ast2520.inc 
PREFERRED_VERSION_linux-aspeed ?= "4.1.15"
#PREFERRED_VERSION_linux-aspeed ?= "4.7"

If 4.7 kernel is not available, can someone confirm whether those improvements are incorporated as part of 4.1.15 kernel of helium itself ?

Thanks in advance,
Karthik Balaguru

**Comment by tfangit** [comment]
@karthikbgt 4.7 is an internal tree we are experimenting. It is not stable and not ready for production use. That's the reason why the line is in comment and we didn't push that branch out. 4.1.15 is the one in production.
