### ISSUE TITLE
How to use QEMU run wedge100 image

### ISSUE THREAD

**Issue by FrankHome** [facebook/openbmc#49]
If I can use some command to run wedge100 image  ,just like "runqemu qemux86"
Help me.
![snip20170513_4](https://cloud.githubusercontent.com/assets/24242110/26025992/9f8c94b2-3825-11e7-95a5-05a34e7f2ebe.png)

**Comment by sumanthbhatt** [comment]
bump

**Comment by tfangit** [comment]
We currently don't support qemu for various OpenBMC boards in this repo.
