### ISSUE TITLE
Is it possible to "freeze" my local source?

### ISSUE THREAD

**Issue by AdrianB-Flex** [facebook/openbmc#52]
One of my bosses wants our complete openbmc implementation frozen and archived locally.  I have explained I don't think that is possible since many repos are pulled during the build process (not to mention the syncing nightmare that would eventually lead to).  But I understand the concern, how would I maintain the code for our product if the source can and will change?

**Comment by tfangit** [comment]
In meta-facebook/conf/distro/openbmc-fb.conf, we defined 'BB_GENERATE_MIRROR_TARBALLS = "1"'. That tells bitbake to generate tarball for all source code downloaded for the build. You can then copy those tarballs into another directory as source mirror and track it under version control. Then modify "SOURCE_MIRROR_URL" to point to the source mirror repo. After that, you will be able to generate your build completely based on your local source.

**Comment by AdrianB-Flex** [comment]
That's good to know.  Thanks Tian.

**Comment by AdrianB-Flex** [comment]
Where are the tarballs saved?

**Comment by AdrianB-Flex** [comment]
Tian, where can I find the tarball?
