### ISSUE TITLE
cat /etc/issue

### ISSUE THREAD

**Issue by AdrianB-Flex** [facebook/openbmc#67]
I believe is supposed to contain the current loaded version of software but mine is empty
How do I get the build string copied to this location?

root@bmc:~# cat /etc/issue
OpenBMC Release

**Comment by covracer** [comment]
It should have a tag or commit ID from git. See: https://github.com/facebook/openbmc/blob/helium/common/recipes-core/base-files/base-files_%25.bbappend

**Comment by AdrianB-Flex** [comment]
I usually tag the branch after I have verified it for release not before.  But I'll give this a try
