### ISSUE TITLE
Random MAC address on each boot

### ISSUE THREAD

**Issue by AdrianB-Flex** [facebook/openbmc#68]
I wrote a local mac into the board id eeprom (wedge_eeprom) and expected that to be used to configure eth0 but on each boot I see a different, presumably randomly generated MAC being used.  Can someone help resolve this please?

**Comment by covracer** [comment]
This init script is what's supposed to read and set the MAC address: https://github.com/facebook/openbmc/blob/aafbf45898f59df72be389bf5a21bc821db9f00d/meta-facebook/meta-cmm/recipes-utils/openbmc-utils/files/eth0_mac_fixup.sh

Maybe you could run it manually with `bash -x` to trace what's happening.

**Comment by AdrianB-Flex** [comment]
This can be closed - was my issue.  EEPROM was not programmed.
