### ISSUE TITLE
Build fails when specifying build directory outside the poky root.

### ISSUE THREAD

**Issue by dnbazhenov** [facebook/openbmc#73]
When I specify the build dir which lies outside the poky (yoctoproject) metadata root, the build fails (see error.log attached).
The attached patch fixes the bug and allows to specify arbitrary build directory.
[0001-Fixup-build-error-in-the-case-where-the-build-dir-is.patch.gz](https://github.com/facebook/openbmc/files/1465921/0001-Fixup-build-error-in-the-case-where-the-build-dir-is.patch.gz)

[error.log](https://github.com/facebook/openbmc/files/1465920/error.log)

**Comment by jmehta** [comment]
Hello @bazhenov-dn, Thank you so much for pointing this out. It would be great to resolve this. 
We would be happy to review and pull the change if you can open a [Pull Request](https://github.com/facebook/openbmc/pulls) for it. 
For now, I am going to close this issue. :)
