### ISSUE TITLE
Wget 308 error

### ISSUE THREAD

**Issue by ck2qsuZT** [facebook/openbmc#78]
https://github.com/facebook/openbmc/blob/aafbf45898f59df72be389bf5a21bc821db9f00d/common/recipes-utils/flashrom/flashrom_0.9.8.bb

returns: 

HTTP request sent, awaiting response... 308 Permanent Redirect
-bash: HTTP: command not found

This is an issue of wget not being able to handle 308 and "an appropriate change is pushed to master now."

https://lists.nongnu.org/archive/html/bug-wget/2017-11/msg00015.html

but it might take some time for wget clients to update so it'll probably be easier to fix it in this file by changing both instances of "http" to "https"

**Comment by D-Nikhil** [comment]
@ck2qsuZT - Thank you for suggesting a workaround which worked perfectly. I faced the same issue while building a wedge100 image.  Are you going to push this patch upstream as well?
