### ISSUE TITLE
Port OpenBMC to Leopard

### ISSUE THREAD

**Issue by bluecmd** [facebook/openbmc#87]
Hi,

I have access to a couple of Leopard servers and I was thinking that it would be really nice to have OpenBMC on them. Is there a specific reason why OpenBMC was never ported to Leopard?

If not, would you be OK with a PR down the road for a potential port?

**Comment by fberndl** [comment]
With some guidance I would like to add support to Leopard and test it with appropriate servers

**Comment by amithash** [comment]
@bluecmd, @fberndl Historically Leopard predated openBMC which was Facebook's previous generation 2 socket OCP server. We decided to use openBMC on TiogaPass our current generation 2 socket OCP server platform. This is the reason why we do not see use-case for porting openBMC to leopard.

There is currently a community developed project for openBMC under Linux Foundation (openbmc.org, Github: https://github.com/openbmc). I would highly recommend joining this community and start collaborating on the porting effort for leopard.

If you need any help, feel free contact me.

**Comment by bluecmd** [comment]
Thanks @amithash! Sounds like a plan.
