### ISSUE TITLE
ipmitool channel support ?

### ISSUE THREAD

**Issue by hans-tseng** [facebook/openbmc#90]
Hi sir:
   I used the "ipmitool channel info" command but it returned the "invalid command".
  And I also checked it completed code, it was 0xc1. 
  Did openbmc does not support channel command?

Hans

**Comment by sdasari73** [comment]
>>Did openbmc does not support channel command?
No it does not. By design, we do NOT enable IPMI commands over LAN (over RMCP protocol). There is limited IPMI commands supported over inband (via kcs) which is extensible.
