### ISSUE TITLE
IPMI interface to BMC

### ISSUE THREAD

**Issue by ACodingfreak** [facebook/openbmc#91]
Hi All,

Is IPMI interface supported by openbmc in Wedge100 ? If Yes, are there any steps to enable IPMI over LAN support ?

Currently I dont see any ipmitool command available in openbmc.

Thanks

**Comment by sdasari73** [comment]
>>Is IPMI interface supported by openbmc in Wedge100 ?
Very limited IPMI commands are supported on in-band. Try using ipmitool on the X86 host and BMC will respond to few of the IPMI commands.
>>If Yes, are there any steps to enable IPMI over LAN support ?
IPMI over LAN (RMCP protocol for Out-of-Band) is NOT supported. 

>>Currently I dont see any ipmitool command available in openbmc.
check the recipe@ https://github.com/facebook/openbmc/tree/helium/common/recipes-support/ipmitool to allow adding ipmitool to your platform image. We are not using ipmitool on Wedge100 platform.

**Comment by ACodingfreak** [comment]
@sdasari73  - Thanks for the reply.

As per the reply, IPMI is only supported on in-band where I run the ipmitool directly in openbmc and not supported in out of the band where I run ipmitool in external host which is connected via LAN to BMC module ? Is my understanding right ?

Any steps on how to build the ipmitool recipe which you have shared in the previous reply ?

Thanks 
Ajith

**Comment by amithash** [comment]
Try adding ipmitool to the platform's image recipe. Checkout fbtp: https://github.com/facebook/openbmc/blob/helium/meta-facebook/meta-fbtp/recipes-core/images/fbtp-image.bb#L49
